In [ ]:
import numpy as np
#import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
# Importing the dataset
dataset = pd.read_csv('/content/dataset1.csv')   # XLSX read_excel  .tsv   
# dataset link = https://drive.google.com/drive/u/0/folders/1EWc1ve3GGw4z3UC_uveeoanC5u5-Qr8W

In [ ]:
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [ ]:
dataset.shape

(10, 4)

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Country    10 non-null     object 
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  10 non-null     object 
dtypes: float64(2), object(2)
memory usage: 448.0+ bytes


In [ ]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values


In [ ]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [ ]:
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [ ]:
from sklearn.preprocessing import LabelEncoder
labelencoder_X = LabelEncoder()
X[:, 0] = labelencoder_X.fit_transform(X[:, 0])
print(X)

[[0 44.0 72000.0]
 [2 27.0 48000.0]
 [1 30.0 54000.0]
 [2 38.0 61000.0]
 [1 40.0 nan]
 [0 35.0 58000.0]
 [2 nan 52000.0]
 [0 48.0 79000.0]
 [1 50.0 83000.0]
 [0 37.0 67000.0]]


In [ ]:
# Data Preprocessing

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the SimpleImputer class 
from sklearn.impute import SimpleImputer 
  

In [ ]:
# Imputer object using the mean strategy and  
# missing_values type for imputation 
imputer1 = SimpleImputer(missing_values = np.nan,  
                        strategy ='mean') 
  

In [ ]:
imputer1

SimpleImputer()

In [ ]:
data = [[12, np.nan, 34], [10, 32, np.nan],  
        [np.nan, 11, 20]] 
  

In [ ]:
data

[[12, nan, 34], [10, 32, nan], [nan, 11, 20]]

In [ ]:
print("Original Data : \n", data) 
# Fitting the data to the imputer object 
imputer1 = imputer1.fit(data) 

# Imputing the data      
data = imputer1.transform(data) 
print("Imputed Data : \n", data)  # column wise

Original Data : 
 [[12, nan, 34], [10, 32, nan], [nan, 11, 20]]
Imputed Data : 
 [[12.  21.5 34. ]
 [10.  32.  27. ]
 [11.  11.  20. ]]


In [ ]:
# Importing the dataset
dataset = pd.read_csv('/content/dataset2.csv')
X = dataset.iloc[:, :].values
#y = dataset.iloc[:, 3].values

In [ ]:
X

array([['Sunny', 1, 'Sunny'],
       ['Sunny', 2, 'Sunny'],
       ['Overcast', 3, 'Overcast'],
       ['Rain', 4, 'Rain'],
       ['Rain', 5, 'Rain'],
       ['Rain', 2, 'Rain'],
       ['Overcast', 3, 'Overcast'],
       ['Sunny', 1, 'Sunny'],
       ['Sunny', 2, 'Sunny'],
       ['Rain', 3, 'Rain'],
       ['Sunny', 4, 'Sunny'],
       ['Overcast', 2, 'Overcast'],
       ['Overcast', 1, 'Overcast'],
       ['Rain', 3, 'Rain']], dtype=object)

In [ ]:
# Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer


In [ ]:
transform =  ColumnTransformer([("Col 0",OneHotEncoder(),[0])], 
                                remainder = 'passthrough')
X = transform.fit_transform(X)


In [ ]:
X

array([[0.0, 0.0, 1.0, 1, 'Sunny'],
       [0.0, 0.0, 1.0, 2, 'Sunny'],
       [1.0, 0.0, 0.0, 3, 'Overcast'],
       [0.0, 1.0, 0.0, 4, 'Rain'],
       [0.0, 1.0, 0.0, 5, 'Rain'],
       [0.0, 1.0, 0.0, 2, 'Rain'],
       [1.0, 0.0, 0.0, 3, 'Overcast'],
       [0.0, 0.0, 1.0, 1, 'Sunny'],
       [0.0, 0.0, 1.0, 2, 'Sunny'],
       [0.0, 1.0, 0.0, 3, 'Rain'],
       [0.0, 0.0, 1.0, 4, 'Sunny'],
       [1.0, 0.0, 0.0, 2, 'Overcast'],
       [1.0, 0.0, 0.0, 1, 'Overcast'],
       [0.0, 1.0, 0.0, 3, 'Rain']], dtype=object)

In [ ]:
transform =  ColumnTransformer([("Column 4 converted",OneHotEncoder(),[4])], 
                                remainder = 'passthrough')
X = transform.fit_transform(X)

In [ ]:
X

array([[0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1],
       [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 2],
       [1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 3],
       [0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 4],
       [0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 5],
       [0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 2],
       [1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 3],
       [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1],
       [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 2],
       [0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 3],
       [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 4],
       [1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 2],
       [1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1],
       [0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 3]], dtype=object)

In [ ]:
transform =  ColumnTransformer([("Outlook_OL0_OL1",OneHotEncoder(),[6])], 
                                remainder = 'passthrough')
X = transform.fit_transform(X)
print(X.astype(int))

[[1 0 0 0 0 0 0 1 0 0 1]
 [0 1 0 0 0 0 0 1 0 0 1]
 [0 0 1 0 0 1 0 0 1 0 0]
 [0 0 0 1 0 0 1 0 0 1 0]
 [0 0 0 0 1 0 1 0 0 1 0]
 [0 1 0 0 0 0 1 0 0 1 0]
 [0 0 1 0 0 1 0 0 1 0 0]
 [1 0 0 0 0 0 0 1 0 0 1]
 [0 1 0 0 0 0 0 1 0 0 1]
 [0 0 1 0 0 0 1 0 0 1 0]
 [0 0 0 1 0 0 0 1 0 0 1]
 [0 1 0 0 0 1 0 0 1 0 0]
 [1 0 0 0 0 1 0 0 1 0 0]
 [0 0 1 0 0 0 1 0 0 1 0]]


In [ ]:
# Importing the dataset
dataset = pd.read_csv('dataset1.csv')   # XLSX read_excel  .tsv     read_csv('d1.tsv',delimiter='\t')
dataset.shape
# divide my dataset into 2 parts - input and output

dataset.info()

X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

# To fill up missing value - To Impute

from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')
imputer = imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])  

from sklearn.preprocessing import LabelEncoder
labelencoder_X = LabelEncoder()
X[:, 0] = labelencoder_X.fit_transform(X[:, 0])
print(X)

# ============================
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Country    10 non-null     object 
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  10 non-null     object 
dtypes: float64(2), object(2)
memory usage: 448.0+ bytes
[[0 44.0 72000.0]
 [2 27.0 48000.0]
 [1 30.0 54000.0]
 [2 38.0 61000.0]
 [1 40.0 63777.77777777778]
 [0 35.0 58000.0]
 [2 38.77777777777778 52000.0]
 [0 48.0 79000.0]
 [1 50.0 83000.0]
 [0 37.0 67000.0]]


In [ ]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

# MInMaxScaler
# Calculate mathematically as an example

In [ ]:
X_test

array([[ 0.13483997, -1.45882927, -0.90166297],
       [ 0.13483997,  1.98496442,  2.13981082]])

In [ ]:
X_train

array([[ 0.13483997,  0.26306757,  0.12381479],
       [-0.94387981, -0.25350148,  0.46175632],
       [ 1.21355975, -1.97539832, -1.53093341],
       [ 1.21355975,  0.05261351, -1.11141978],
       [-0.94387981,  1.64058505,  1.7202972 ],
       [ 1.21355975, -0.0813118 , -0.16751412],
       [-0.94387981,  0.95182631,  0.98614835],
       [-0.94387981, -0.59788085, -0.48214934]])